/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.google.code.gson:gson:2.8.5")
    implementation("org.testng:testng:6.14.3")
    implementation("org.jsoup:jsoup:1.11.3")
    implementation("us.codecraft:webmagic-core:0.7.3")
    implementation("us.codecraft:webmagic-extension:0.7.3")
    implementation("commons-io:commons-io:2.7")
    implementation("net.sourceforge.htmlunit:htmlunit:2.37.0")
    implementation("org.dom4j:dom4j:2.1.3")
    implementation("mysql:mysql-connector-java:8.0.16")
    implementation("org.apache.poi:poi:4.0.1")
    implementation("com.google.inject:guice:4.1.0")
    implementation("org.apache.commons:commons-lang3:3.7")
    implementation("javax.mail:javax.mail-api:1.6.0")
    implementation("org.apache.logging.log4j:log4j-core:2.14.0")
    implementation("org.apache.logging.log4j:log4j-api:2.14.0")
    implementation("org.seleniumhq.selenium:selenium-server:3.14.0")
    implementation("io.rest-assured:xml-path:3.1.1")
    implementation("com.google.guava:guava:23.0")
    implementation("org.apache.velocity:velocity:1.7")
    implementation("org.jacoco:jacoco-maven-plugin:0.8.6")
    implementation("org.apache.pdfbox:pdfbox:2.0.15")
    implementation("javax.mail:mail:1.4.7")
    implementation("org.apache.commons:commons-csv:1.5")
    testImplementation("io.rest-assured:rest-assured:3.1.1")
    testImplementation("org.uncommons:reportng:1.1.4")
}

group = "com.dbyl"
version = "1.4.2"
description = "framework"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.named<Test>("test") {
    useTestNG()
}
